# Generated by Django 5.2.3 on 2025-08-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_developers_testers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect_Screen_Shots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_img', models.ImageField(blank=True, null=True, upload_to='defectimg')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.defects_details')),
            ],
        ),
    ]
