# Generated by Django 5.2.3 on 2025-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_alter_defects_details_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects_details',
            name='assigned_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='defects_details',
            name='assigned_to',
            field=models.CharField(max_length=100),
        ),
    ]
