# Generated by Django 5.2.3 on 2025-08-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_alter_defects_details_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects_details',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.testers'),
        ),
        migrations.AlterField(
            model_name='defects_details',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defects.developers'),
        ),
    ]
